# Generated by Django 4.0.4 on 2022-05-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects_and_places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='room',
        ),
        migrations.AddField(
            model_name='place',
            name='room_of_storage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects_and_places.room'),
        ),
    ]
