# Generated by Django 4.0.4 on 2022-05-16 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects_and_places', '0002_room_remove_place_room_place_room_of_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='room_of_storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects_and_places.room'),
        ),
    ]
